package org.braingrow.gritter.rules

import java.lang.String
import org.braingrow.gritter.drools.twitterutil.IdentifiableText
import scala.Tuple3
import java.util.concurrent.CopyOnWriteArrayList
import java.util.ArrayList

global org.braingrow.gritter.drools.ActorBackedMessageNotifier notifier;

declare IdentifiableText
   @role(event)
end

rule "Collect Words"
   dialect "mvel"
   when
    $idText:IdentifiableText()
    $list: ArrayList() from accumulate($it:IdentifiableText() over window:time(60m),top10($it))
   then
    notifier.onMessage($list);
end


