package org.braingrow.gritter.rules

import java.lang.String
import org.braingrow.gritter.drools.twitterutil.IdentifiableText
import scala.Tuple3
import java.util.concurrent.CopyOnWriteArrayList
import java.util.ArrayList

global org.braingrow.gritter.drools.ActorBackedMessageNotifier notifier;

declare String
   @role(event)
end

rule "Collect Words"
   dialect "mvel"
   when
    $timeZone:String()
    $list: ArrayList() from accumulate($tz:String() over window:time(60m),top10Timezones($tz))
   then
    notifier.onMessage($list);
end


