package org.braingrow.gritter.rules

import java.lang.String
import scala.Tuple2
import java.util.concurrent.CopyOnWriteArrayList

global org.braingrow.gritter.drools.ActorBackedMessageNotifier listReceiver;

declare String
   @role(event)
end

declare Tuple2
    @role(event)
end

rule "A word"
   dialect "mvel"
   when
    $word:String  ()
    $count: Number (intValue > 6) from accumulate($word2:String(toString == $word) over window:time(1m) , count($word2))
   then
    $word.intern()
    insert( new Tuple2($word,$count))
end


rule "Remove duplicates 1" salience 10
   dialect "mvel"
   when
    $tuple1:Tuple2($word:_1,$count:_2)
    $tuple2:Tuple2(_1==$word, this before $tuple1 )
   then
    retract ($tuple2);
end




rule "Get word list"
   dialect "mvel"
   when
    $wordlist: CopyOnWriteArrayList() from collect ($t1:Tuple2())

   then
   System.out.println($wordlist)
    listReceiver.onMessage($wordlist);
end